# /app/config.yml
chatbot:
  name: "RAG_BOT"
Key_File: "key.env"
OpenAI:
  chat_temp: 0.0
  llm_temp: 0.0
  model: "gpt-4-1106-preview"
Scraper:
  DATA_DIR: '/app/src/scraper/scraped_data'
  USER_AGENTS:
    - "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.82 Safari/537.36"
    - "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Firefox/89.0"
    - "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.3 Safari/605.1.15"
Qdrant:
  url: "http://RAG_BOT_QDRANT:6333"
  vector_size: "768"
Embedding_Type: "local" #Can be 'local' or 'openai'